### ISSUE TITLE
path option question

### ISSUE THREAD

**Issue by persianphilosopher** [rougin/weasley#1]
Hi there,

I am very glad to run across your work. It's wonderful and I look forward to trying out many of your repos.

I have run into a small issue and it is perhaps my mistaken use of weasley.  I tried:

`vendor/bin/weasley make:middleware TestMiddleware`

and it worked great and it created it `src/Http/Middleware/` . I am used to setting up an app (not src) folder. I saw in the code that one can feed the path as an option.  When I tried

`vendor/bin/weasley make:middleware TestMiddleware --path app`

I was glad to see that it put it in the app folder but it created it in `app/TestMiddleware` with no subfolder *but* the namespace says: `namespace App\Http\Middleware;`

Maybe I am not using the path option correctly. But it would be great if it is possible to tell weasely to use a folder other than `src` and to still have the proper subfolders and namespaces created. 

Thank you for all your work.

**Comment by rougin** [comment]
Hello @persianphilosopher,

Thank you for using this library. Regarding on the changing of the namespace, you need include `--namespace`:

``` bash
vendor/bin/weasley make:middleware TestMiddleware --path app --namespace="App\Middleware"
```

**Comment by rougin** [comment]
You can also change the author with the `--author` option and package name with the `--package` option.

**Comment by persianphilosopher** [comment]
Thank you so much for your help! 

I think it would be great to add this to the console help or to the README.md.
